{
	"version": 1627749108,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/clickanywheretocontinue-sheet0.png",
		"images/background-sheet0.png",
		"images/back1-sheet0.png",
		"images/background2-sheet0.png",
		"images/paws-sheet0.png",
		"images/themagicalkingdomandthewitch-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/howtoplay-sheet0.png",
		"images/settings-sheet0.png",
		"images/s5-sheet0.png",
		"images/s4-sheet0.png",
		"images/s3-sheet0.png",
		"images/s2-sheet0.png",
		"images/s1-sheet0.png",
		"images/leaderboard-sheet0.png",
		"images/default-sheet0.png",
		"images/grassbase.png",
		"images/dirtbase.png",
		"images/mc-sheet0.png",
		"images/mc-sheet1.png",
		"images/mc-sheet2.png",
		"images/enemy1-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/enemy2-sheet1.png",
		"images/chest-sheet0.png",
		"images/health-sheet0.png",
		"images/door-sheet0.png",
		"images/e1-sheet0.png",
		"images/e2-sheet0.png",
		"images/e3-sheet0.png",
		"images/flyingwood.png",
		"images/flying1-sheet0.png",
		"images/flying3-sheet0.png",
		"images/flying2-sheet0.png",
		"images/flyingmid.png",
		"images/grasshillleft-sheet0.png",
		"images/grasshillleft2-sheet0.png",
		"images/grasshillright-sheet0.png",
		"images/grasshillright2-sheet0.png",
		"images/howtoplay2-sheet0.png",
		"images/slash-sheet0.png",
		"images/darken.png",
		"images/popupbase-sheet0.png",
		"images/gameover-sheet0.png",
		"images/paused-sheet0.png",
		"images/youwon-sheet0.png",
		"images/continuebutton-sheet0.png",
		"images/mainmenubutton-sheet0.png",
		"images/restartbutton-sheet0.png",
		"images/spritefont.png",
		"images/group-sheet0.png",
		"images/soundfx-sheet0.png",
		"images/characterfx2-sheet0.png",
		"images/witch-sheet0.png",
		"images/stage2button-sheet0.png",
		"images/stage3button-sheet0.png",
		"images/stage4button-sheet0.png",
		"images/stage1button-sheet0.png",
		"images/group2-sheet0.png",
		"images/stage-sheet0.png",
		"images/stage2-sheet0.png",
		"images/stage3-sheet0.png",
		"images/stage4-sheet0.png",
		"images/createdby-sheet0.png",
		"images/kelompok-sheet0.png",
		"images/group3-sheet0.png",
		"images/credit-sheet0.png",
		"media/click.ogg",
		"media/jingle win.ogg",
		"media/collect gem.ogg",
		"media/collect key.ogg",
		"media/enemyhit.ogg",
		"media/hit.ogg",
		"media/jingle lose.ogg",
		"media/mattoglseby - 1.ogg",
		"media/theme1.ogg",
		"media/theme2.ogg",
		"media/theme3.ogg",
		"media/theme4.ogg",
		"media/time of heroes.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"background 1.png"
	]
}